### ISSUE TITLE
[Question] allow Shape sleep

### ISSUE THREAD

**Issue by arpu** [pmndrs/cannon-es#101]
Hey,

would it be possible to allow Shape sleep?  the idea is to have one body with multiple Trimesh Shapes
and lets the Shape sleep if the Character is not near. ( near distance could be done with bvh https://github.com/gkjohnson/three-mesh-bvh)

**Comment by arpu** [comment]
a other Idea is use a option like the world.broadphase.useBoundingBoxes = true;
with the bvh boundingTree

**Comment by marcofugaro** [comment]
What's wrong with Body sleep?

https://pmndrs.github.io/cannon-es/examples/sleep

**Comment by arpu** [comment]
Yes i looked at this too, but with this i need to create a body for all Trimeshes, not sure if this is a problem or not 

![Bildschirmfoto von 2021-07-14 13-38-44](https://user-images.githubusercontent.com/14173/125617485-25f05476-59d3-4385-9b85-fbf4e4060731.png)


right now i create one body with multible Trimeshes  and use  world.broadphase.useBoundingBoxes

**Comment by marcofugaro** [comment]
Should work the same, have you tested it?

**Comment by arpu** [comment]
no, but for one Model it would make sense to use one body? and multiple Shapes

**Comment by arpu** [comment]
ok with multible bodys and one Trimesh per body, sleeping works well!  
not sure if this has any disadvantage.

closing for now
