### ISSUE TITLE
I cannot migrate a simple example from cannon to cannon-es

### ISSUE THREAD

**Issue by 8Observer8** [pmndrs/cannon-es#106]
I have a very simple TypeScript example in cannon that just print a gravity:

```
import "cannon";

function main()
{
    const physicsWorld = new CANNON.World();
    physicsWorld.gravity.set(0, -9.82, 0);
    console.log("gravity = ", physicsWorld.gravity);
}

main();
```

You can run it on playground: https://plnkr.co/edit/EoxKFFYZgtXnTTEX?preview

Source code on GitHub with cannon: https://github.com/8Observer8/hello-cannon-ts
Source code on GitHub with cannon-es: https://github.com/8Observer8/hello-cannon-es-ts

When I try to change "cannon" to "cannon-es", for example, this line:

```
import "cannon"
```

on this line:

```
import * as CANNON from "cannon-es";
```

I get this error: `Uncaught ReferenceError: exports is not defined` and this error: `Uncaught TypeError: Cannot read property 'World' of undefined`

![image](https://user-images.githubusercontent.com/3908473/131516723-3b25b833-0fe6-40f6-90a4-52c89db76ef0.png)

**Comment by marcofugaro** [comment]
It's an issue with your bundler, please add cannon-es as a dependency and make sure it is included by browserify.

**Comment by 8Observer8** [comment]
I use AMD (Asynchronous Module Definition) and RequireJS instead Browserify for this example. I added cannon-es as dependency. You can look it [here](https://github.com/8Observer8/hello-cannon-es-ts). I made the same example like with cannon. cannon works but cannot does not work with the same settings. I added a link to the hello-cannon-es-ts in the topic.

[requireConfig.ts](https://github.com/8Observer8/hello-cannon-es-ts/blob/master/src/client/requireConfig.ts)
```
requirejs.config({
    baseUrl: "js",
    paths: {
        "cannon-es": "https://cdn.jsdelivr.net/npm/cannon-es@0.18.0/dist/cannon-es.cjs.min"
    }
});

requirejs(["main"], () => { });
```

**Comment by marcofugaro** [comment]
It does not work because that's a commonjs module. You need an umd module to make it work with RequireJS.

Cannon-es does not expose an umd module. Please use esmodules directly or alternatively use any bundler.

**Comment by 8Observer8** [comment]
Thank you very much.

**Comment by 8Observer8** [comment]
It's sad that it doesn't work like this:

```
<!DOCTYPE html>
<html lang="en">

<head>
    <script src="https://cdn.jsdelivr.net/npm/cannon-es@0.18.0/dist/cannon-es.js"></script>
</head>

<body>
    <script>
        const gravity = new CANNON.Vec3(0, -9.82, 0);
        console.log(gravity);
    </script>
</body>

</html>
```

But cannon works very well:

```
<!DOCTYPE html>
<html lang="en">

<head>
    <script src="https://cdn.jsdelivr.net/npm/cannon@0.6.2/build/cannon.min.js"></script>
</head>

<body>
    <script>
        const gravity = new CANNON.Vec3(0, -9.82, 0);
        console.log(gravity);
    </script>
</body>

</html>
```

I will use cannon but I will get examples of cannon-es.

**Comment by 8Observer8** [comment]
> I receive these errors:
Wow! I found how to solved these errors in this tutorial: https://sbcode.net/threejs/physics-cannonjs/

Output:
```
Vec3 {x: 0, y: -9.82, z: 0}
```

```
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Example</title>
</head>

<body>
    <script type="module">
        import * as CANNON from "https://cdn.jsdelivr.net/npm/cannon-es@0.18.0/dist/cannon-es.js";

        const gravity = new CANNON.Vec3(0, -9.82, 0);
        console.log(gravity);
    </script>
</body>

</html>
```

**Comment by 8Observer8** [comment]
> It's sad that Cannon-es doesn't work like this

Sorry, I see now that the Cannon-es examples already work like this - they have the `type="module"` script attribute.

**Comment by 8Observer8** [comment]
> It's an issue with your bundler, please add cannon-es as a dependency and make sure it is included by browserify.

Cannon-es works with Browserify and TypeScript without problems. I need to solve the problem with Require.js AMD

> It does not work because that's a commonjs module. You need an umd module to make it work with RequireJS.
I will try to use UMD. When I try just replace "AMD" to "UMD" it says that `ReferenceError: exports is not defined`:

tsconfigs/tsconfig.debug.json
```
{
    "extends": "./tsconfig.json",
    "compilerOptions": {
        "module": "UMD",
        "sourceMap": true,
        "types": [
            "cannon-es",
            "requirejs"
        ]
    }
}
```

tsconfigs/tsconfig.json
```
{
    "compilerOptions": {
        "target": "ES5",
        "outDir": "../public/js"
    },
    "include": [
        "../src/client/**/*.ts"
    ]
}
```

tsconfigs/tsconfig.release.json
```
{
    "extends": "./tsconfig.json",
    "compilerOptions": {
        "module": "CommonJS",
        "sourceMap": false,
        "types": [
            "node"
        ]
    },
    "exclude": [
        "../src/client/requireConfig.ts"
    ]
}
```

src/client/requireConfig.ts

```
requirejs.config({
    baseUrl: "js",
    paths: {
        "cannon-es": "https://cdn.jsdelivr.net/npm/cannon-es@0.18.0/dist/cannon-es.cjs.min"
    }
});

requirejs(["main"], () => { });
```

src/client/main.ts
```
import * as CANNON from "cannon-es";
// import "cannon-es";

function main()
{
    const physicsWorld = new CANNON.World();
    physicsWorld.gravity.set(0, -9.82, 0);

    console.log("gravity = ", physicsWorld.gravity);
    const outputElement = document.getElementById("output");
    outputElement.innerHTML = "gravity = " + physicsWorld.gravity;
}

// Debug
main();

// Release
// window.onload = () => main();
```

index.html
```
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Hello Cannon-ES. TypeScript</title>

    <!-- Debug -->
    <script data-main="js/requireConfig"
        src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js"></script>
    <!-- Release -->
    <!-- <script src="js/bundle.min.js"></script> -->
</head>

<body>
    <div id="output"></div>
</body>

</html>
```

package.json
```
{
  "name": "hello-cannon-es-ts",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "debug": "tsc -p tsconfigs/tsconfig.debug.json",
    "compile": "tsc -p tsconfigs/tsconfig.release.json",
    "bundle": "browserify public/js/main.js -o public/js/bundle.js",
    "minify": "uglifyjs public/js/bundle.js -o public/js/bundle.min.js",
    "release": "npm run compile && npm run bundle && npm run minify"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "cannon-es": "^0.18.0",
    "requirejs": "^2.3.6"
  },
  "devDependencies": {
    "@types/requirejs": "^2.1.32"
  }
}
```

**Comment by marcofugaro** [comment]
>  I just need to add type="module" as a script attribute

Yeah, that's how es modules work (cannon-es is an es module). [Read more about it here](https://flaviocopes.com/es-modules/)

> I need to solve the problem with Require.js and AMD.

My advice would be to stop using Require.js, it's an antiquated library and has been made obsolete with the introduction of es modules.

Closing since this is not related to cannon-es.

**Comment by 8Observer8** [comment]
Solution 2. Browserify and [UglifyJS](https://www.npmjs.com/package/uglify-js)

1. Install Browserify, UglifyJS, and TypeScript globally: `npm i -g browserify uglify-js typescript`
2. Copy these commands to `package.json`:
```
  "scripts": {
    "debug": "browserify src/client/main.ts -p tsify --debug -o public/js/bundle.js",
    "bundle-release": "browserify src/client/main.ts -p tsify -o public/js/temp-bundle.js",
    "minify-release": "uglifyjs public/js/temp-bundle.js -o public/js/bundle.js",
    "release": "npm run bundle-release && npm run minify-release"
  }
```
3. Add this line to <body> in 'index.html': `<script src="js/bundle.js"></script>`
4. Use this command to debug: `npm run debug`. You can set breakpoints in your browser in TypeScript files but I cannot set breakpoints in VSCode with the deprecated Chrome Extension from Microsoft
5. Use this command to release: `npm run debug`. Your application will be compressed to `bundle.js`

**Comment by 8Observer8** [comment]
But the main problem was not solved. My main goal is to place my TypeScript examples with cannon-es on some Playground like I made it with Cannon.js, Require.js, glMatrix and pure WebGL: https://plnkr.co/edit/ZrG1OFKjOyxsFbr3?preview

![colored-objects-from-dae-and-cannonjs](https://user-images.githubusercontent.com/3908473/161374803-bbb1abb2-eb56-4467-bad8-c0fedb315c47.gif)

Plunker and Require.js allows to run Jasmine Unit Tests in TypeScirpt: https://plnkr.co/edit/77Ex6gPTBxQyyXNML9tk?preview 

Maybe someone knows how to run cannon-es with TypeScript on Plunker or on another playground with any bunder. I tried some of them. Please, publish links on examples with cannon-es and TypeScript on some playgrounds.
