### ISSUE TITLE
Collision detection throws an error: bodyb.position.vsub is not a function

### ISSUE THREAD

**Issue by abraxous** [pmndrs/cannon-es#112]
Hi, I'll get right into it.

![ihgvbn](https://user-images.githubusercontent.com/15070699/141510409-6542dff3-add1-4195-81b4-2e953b0c530c.PNG)

This is the error as displayed in the console. I will also include my own functions which appear in this traceback.
![kjhbvbnm](https://user-images.githubusercontent.com/15070699/141510844-6931983a-9a6c-42df-afa7-336966d8f1bd.PNG)
![khb](https://user-images.githubusercontent.com/15070699/141511181-34477a0e-f553-467a-b87e-429b087aea4f.PNG)

What I've done is pretty simple so I'm struggling to figure out what I could have broken. I think perhaps it's trying to access bodyb.position.vsub where bodyb.position doesn't have vsub, or perhaps bodyb doesn't have position at all. Perhaps I'm adding bodies to the world incorrectly?

![kbn](https://user-images.githubusercontent.com/15070699/141512723-af9120a3-6e9e-4fd4-908f-60da226f5aab.PNG)

This is the block where I define the only dynamic body in the scene. It's more than likely the error here is on my part but I appreciate any help.

**Comment by marcofugaro** [comment]
Hey, this is probably an error of configuration of the static/dynamic bodies.

Could you share a full example? I don't have enough info to debug your code.

**Comment by marcofugaro** [comment]
Closing for unactivity
