### ISSUE TITLE
Fly & DYNAMIC

### ISSUE THREAD

**Issue by McRain** [pmndrs/cannon-es#114]
Hello. I am trying to create a body (DYNAMIC), with a mass = 0 (for the release of flight and hovering in the air). The body must move through velocity and collide with other bodies. But if I set the mass to 0 - the body becomes STATIC ? Gravity world.gravity.set (0, -9.87, 0)
How can I implement a body that is not affected by gravity?
Thanks for the tip

**Comment by marcofugaro** [comment]
You have two possibilities, you either don't put any gravity (`world.gravity.set (0, 0, 0)`), or you add a force opposite to the gravity before each step (`body.applyForce(new CANNON.Vec3(0, 9.87, 0))`).

You can do this each frame, or in the `preStep` callback as demonstrated in [this example](https://pmndrs.github.io/cannon-es/examples/callbacks)

**Comment by marcofugaro** [comment]
You're welcome!
