### ISSUE TITLE
Kinematic body collision documentation

### ISSUE THREAD

**Issue by Wuzzie** [pmndrs/cannon-es#115]
Hi, I'm trying to find out how to make a kinematic body not pass-through static objects but I'm struggling to find documentation/examples for this.

I've tried the event "beginContact" but there isn't any contact info similar to what is shown in the "collide" event for dynamic bodies.

Is there any way in "beginContact" or perhaps a different event that can give any face-normal information about a collision?

**Comment by marcofugaro** [comment]
You probably need to use a dynamic body if you want the interaction with the static body.

Could you explain maybe what you're trying to achieve?

**Comment by Wuzzie** [comment]
I'm trying to create a character controller with some ported quake movement code. It has it's own friction calculations etc and there are some very undesirable bugs happening with a dynamic body. There are some 'hacks' I'm doing to get it working but there is a lot issues created by me essentially trying to counteract default physics behaviours innate to dynamic bodies.

If for example the beginContact event gave the normal of the face that my kinematic body collided with then I would have all the information I need to make this character controller behave as I'd hope to.

I briefly looked before the holidays and I haven't started again just yet but I was thinking maybe there was some way to manually call the same collision code in cannon that's run for dynamic bodies?

**Comment by marcofugaro** [comment]
> If for example the beginContact event gave the normal of the face that my kinematic body collided with then I would have all the information I need to make this character controller behave as I'd hope to.

In my experience, with physics engines you can't really override the default behaviour of physics.

But if you want to do something like this, you can use the `collide` event (is called at the same time of `beginContact`) and apply a force to the body relative to the `contact` info as you specified.

**Comment by Wuzzie** [comment]
I am currently doing so to move the body along terrains and such with a dynamic body.

But say for example you stand on a slope, the dynamic body slides down when I'd like it to not...

Or you fall from a height and you bounce or in the case of a slope you might slip a distance down it...

Or how without setting the friction between the dynamic body and terrain to 0 you essentially get double friction because the intent is to use quake's friction calculations...

I have 'hacks' for all of these but...

All of these interactions don't exist for kinematic bodies and a kinematic body is the perfect blank slate for setting up much more simplistic ways of controlling something in a non-realistic way and a body with no simulated physics but with full collision information would be ideal for my purposes.

Also thank you for your replies. I appreciate the help greatly!

**Comment by marcofugaro** [comment]
You're welcome, closing!
