### ISSUE TITLE
Documentation website

### ISSUE THREAD

**Issue by andrezero** [pmndrs/cannon-es#12]
Hey all!

Arriving from https://github.com/schteppe/cannon.js/issues/438 and very happy to  see a fork actively maintanted. 

The README here still says "Visit the original project for full documentation and examples." but the reality is the original project is "[...] slowly disintegrating. Piece by piece." :-D 

I see everything is typescripted now, so there must be some good tools out there now, better than YUI for sure!

How can we help get this documentation website up?

**Comment by codynova** [comment]
Hi @andrezero, good timing - new documentation using the Typedoc generator and TSDoc parser are a work in progress as of today

**Comment by codynova** [comment]
For anyone discovering this issue from the original cannon.js repo, you can still find perfectly working documentation here:

http://schteppe.github.io/cannon.js/docs/

**Comment by andrezero** [comment]
> For anyone discovering this issue from the original cannon.js repo, you can still find perfectly working documentation here:
> 
> http://schteppe.github.io/cannon.js/docs/

for anyone following that link, heads up: note the `http://` ;-)
