### ISSUE TITLE
Simplify world stepping

### ISSUE THREAD

**Issue by whoiskonstantin** [pmndrs/cannon-es#126]
Why we pass only the `timeStep` as an argument when we invoke `.step()` for the first time?

```javascript
// Start the simulation loop
const timeStep = 1 / 60 // seconds
let lastCallTime
function animate() {
  requestAnimationFrame(animate)

  const time = performance.now() / 1000 // seconds
  if (!lastCallTime) { // ???
    world.step(timeStep) // ???
  } else {
    const dt = time - lastCallTime
    world.step(timeStep, dt)
  }
  lastCallTime = time
}
// Start the simulation loop
animate()
```

The code below "seems" to work exactly the same.
```javascript
// Start the simulation loop
const timeStep = 1 / 60 // seconds
let lastCallTime = performance.now() / 1000 // seconds
function animate() {
  requestAnimationFrame(animate)
  
  const time = performance.now() / 1000 // seconds
  const dt = time - lastCallTime
  world.step(timeStep, dt)
  lastCallTime = time
}
// Start the simulation loop
animate()
  ```

**Comment by marcofugaro** [comment]
Because the second argument to the `step` function is the time elapsed since last call. This value has to be greather than the `timeStep` (1 / 60), othewise the world won't step.

In your example, the world isn't stepping on the first `animate()` call, but it starts at the second one.

**Comment by marcofugaro** [comment]
We could probably do this internally

**Comment by whoiskonstantin** [comment]
@marcofugaro Oh wow! You have simplified it so much! For some reason I missed the notification from your response. Thank you!
