### ISSUE TITLE
GridBroadphase is not working

### ISSUE THREAD

**Issue by fuqiang915** [pmndrs/cannon-es#130]
world.broadphase = new CANNON.GridBroadphase(); // this will carsh my page

**Comment by rogerscg** [comment]
When you say it crashes your page, what error are you getting? From what I understand, GridBroadphase is incomplete.

**Comment by marcofugaro** [comment]
It is incomplete, please use the default `NaiveBroadphase`

Source: https://github.com/schteppe/cannon.js/issues/120#issuecomment-33665088
