### ISSUE TITLE
The fixedStep method was not found, and the latest version has not been updated to npm?

### ISSUE THREAD

**Issue by bihongbin3027** [pmndrs/cannon-es#136]
![image](https://user-images.githubusercontent.com/15045200/150056771-d24259fa-8dbf-4772-b9a4-fa2817f08099.png)

**Comment by marcofugaro** [comment]
Sorry, forgot to publish haha.

`v0.19.0` is now online: https://github.com/pmndrs/cannon-es/releases/tag/v0.19.0
