### ISSUE TITLE
Unused Code?

### ISSUE THREAD

**Issue by d3x0r** [pmndrs/cannon-es#138]
https://github.com/pmndrs/cannon-es/blob/master/src/world/World.ts#L501-L506 

This section of code that is supposed to back step the quaternion doesn't appear to actually do anything.
The target vector `interpolatedQuaternion` is only defined in body, and set here, but never read.

`previousQuaternion`  https://github.com/pmndrs/cannon-es/blob/master/src/objects/Body.ts#L941-L942  
Is updated from the current... but again, the integration result is actually unused...

Maybe it should be?  I'm not proposing it's dead code, just still incomplete?

**Comment by marcofugaro** [comment]
It is actually used in the [canvas_interpolation](https://pmndrs.github.io/cannon-es/examples/canvas_interpolation) example, it's useful for multiplayer physics.
