### ISSUE TITLE
when two bunny collide，my browser stuck,is there any way to make it behave smoothly

### ISSUE THREAD

**Issue by yasuomang** [pmndrs/cannon-es#146]
when i create tow custom shape in the world like bunny,my browser stuck when they collide

**Comment by marcofugaro** [comment]
Hey, you should use a ConvexPolyhedron instead of a Trimesh, see the bunny example https://pmndrs.github.io/cannon-es/examples/bunny

**Comment by yasuomang** [comment]
> schteppe#278
when i create tow bunny like the bunny example https://pmndrs.github.io/cannon-es/examples/bunny. The FPS dropped down to only 1,and my scene depend on highly realistic,so i can not use box or convex hull.I have to create complex shape with a lot of vertices and faces like the bunny.
![image](https://user-images.githubusercontent.com/62331159/161363008-98fba1e1-63e7-429e-ad77-3cf49c17580a.png)

**Comment by yasuomang** [comment]
> Hey, you should use a ConvexPolyhedron instead of a Trimesh, see the bunny example https://pmndrs.github.io/cannon-es/examples/bunny

when i create two bunny like the bunny example https://pmndrs.github.io/cannon-es/examples/bunny. The FPS dropped down to only 1,and my scene depend on highly realistic,so i can not use box or convex hull.I have to create complex shape with a lot of vertices and faces like the bunny.
![image](https://user-images.githubusercontent.com/62331159/161363008-98fba1e1-63e7-429e-ad77-3cf49c17580a.png)

**Comment by donmccurdy** [comment]
_copied from https://github.com/schteppe/cannon.js/issues/278#issuecomment-1098070887 —_

The more geometry you have in your simulation the more expensive it will be. Especially if that geometry cannot be simplified to a convex hull or simpler shapes, which are faster for collision detection. Perhaps some physics engines have optimizations to handle a bit more (I don't know), but additional mesh detail is never free. A high-quality video game (for example) is not going to do collision detection on the same high-detail meshes they use to render, they'll use much simpler collision geometries instead.
