### ISSUE TITLE
Request for Soft Body Physics Feature in Cannon-es

### ISSUE THREAD

**Issue by barisskas** [pmndrs/cannon-es#199]
Hello,

I am currently working on a project where I require physics simulations for soft bodies, similar to the functionality available in the Ammo.js library. Through my research and testing, I've come to understand that Cannon-es primarily supports rigid body physics, which unfortunately doesn't meet my project's requirements for more complex, deformable soft body simulations.

For context, I am trying to replicate the physics of a deformable ball, akin to the one demonstrated in Ammo.js's soft body volume demo. The key characteristics needed are the ability for the object to deform upon impact and interact with its environment in a realistic, physically accurate manner.

Could you provide any insights on whether soft body physics is a feature that might be considered for future development in Cannon-es? Additionally, if there are any current workarounds or planned updates that could accommodate this type of physics simulation, I would greatly appreciate learning more about them.

Thank you for your time and for the continuous development of this great library. Looking forward to any guidance or suggestions you could provide.

**Comment by isaac-mason** [comment]
Adding soft body support would be a reasonably big undertaking, and cannon isn't being actively developed right now. You can safely assume this functionality won't get added unless someone starts driving development of cannon again.

**Comment by barisskas** [comment]
Thank you for your explanatory response regarding the project. Understanding that cannon-es is not actively being developed and thus the likelihood of adding soft body support is minimal, is significant for me. However, there's still hope that in the future, someone might rejuvenate the project and consider implementing such features. With this optimism, I will continue to monitor the project's progress. 👍
