### ISSUE TITLE
Examples: include example code of importing a HCAD convex hull from a GLTF file

### ISSUE THREAD

**Issue by samuelbelolo** [pmndrs/cannon-es#53]
Hello, 
Thanks for maintaining cannon! 

I have an error when I create ConvexPolyhedron, I must miss something 

I have a few errors when creating a ConvexPolyhedron Body : 
`cannon-es.js:2247 .faceNormals[0] = Vec3(0,0,-0.9999999999999999) looks like it points into the shape? The vertices follow. Make sure they are ordered CCW around the normal, using the right-hand rule.`

My process : 
- Loading a mesh with a buffer geometry from an HCAD convex decomposition 
- I retrieve the faces & vertex to create the cannon body 

Code : 
```
CreateConvexPolyhedron(geometry, scaleVec) {
        if (!geometry.vertices) {
            geometry = new THREE.Geometry()
                .fromBufferGeometry(geometry)
                .scale(scaleVec.x, scaleVec.y, scaleVec.z)
            geometry.mergeVertices()
            geometry.computeBoundingSphere()
            geometry.computeFaceNormals()
        }
        const points = [],
            faces = []
        points = geometry.vertices.map(function (v) {
            return new CANNON.Vec3(v.x, v.y, v.z)
        })

        faces = geometry.faces.map(function (f) {
            return [f.a, f.b, f.c]
        })
        return new CANNON.ConvexPolyhedron({ vertices: points, faces })
    }
```

Help would be more than welcome :) 

Thanks

**Comment by samuelbelolo** [comment]
Well, I figured it out, 

Here the explanation & fix: I need to convert my geometry in a ConvexGeometry

here's the workflow : 
```js
CreateConvexPolyhedron(geometry, scaleVec) {
// scaleVec : Because my mesh is originary from a GLTF scene, 
// need to scale it with the world scale coming from : clone.getWorldScale()
        if (!geometry.vertices) {
            geometry = new THREE.Geometry() // create geometry
                .fromBufferGeometry(geometry) // from buffer
                .scale(scaleVec.x, scaleVec.y, scaleVec.z) // scale it because coming from gltf scene
            geometry.mergeVertices()
            geometry.computeBoundingSphere()
            geometry.computeFaceNormals()
        }

// ConvexGeometry come from 
// import { ConvexGeometry } from 'three/examples/jsm/geometries/ConvexGeometry'
        geometry = new ConvexGeometry(geometry.vertices) // create a convex geometry 

        const points = [], // array of Cannon Vec3
            faces = [] // array of array of faces see below

        points = geometry.vertices.map(function (v) {
            return new CANNON.Vec3(v.x, v.y, v.z)
        })

        faces = geometry.faces.map(function (f) {
            return [f.a, f.b, f.c]
        })
        return new CANNON.ConvexPolyhedron({ vertices: points, faces :  faces })
    }
```

Let me know if you find better ways/improvements/enhancement

**Comment by marcofugaro** [comment]
Hey, thanks for the snippets.

Yeah my approach is really similar:

```js
const hull = gltf.scene
const hullBody = new CANNON.Body({ mass: 1 })

hull.children.forEach((hullPart) => {
  const geometry = new THREE.Geometry().fromBufferGeometry(hullPart.geometry)

  const vertices = geometry.vertices.map((v) => new CANNON.Vec3().copy(v))
  const faces = geometry.faces.map((f) => [f.a, f.b, f.c])
  const normals = geometry.faces.map((f) => new CANNON.Vec3().copy(f.normal))

  // Construct polyhedron
  const hullPartShape = new CANNON.ConvexPolyhedron({ vertices, faces, normals })

  // Add to compound
  hullBody.addShape(hullPartShape)
})
world.addBody(hullBody)
```

We should improve the [bunny.html]() example and include an example of importing the convex hull from a gltf file. 

Thanks for the issue!

**Comment by samuelbelolo** [comment]
No problem, 
Indeed I could retrieve the normal like this.

the merge vertice methods seem pretty interesting in order to reduce the number of vertices for performance.

**Comment by marcofugaro** [comment]
> the merge vertice methods seem pretty interesting in order to reduce the number of vertices for performance.

True, in my case I exported the convex hull directly from Blender, and I did the mergeVertices optimization there. However it shouldn't be necessary since the hulls created by V-HCAD are already optimized.

**Comment by samuelbelolo** [comment]
Indeed, thanks for maintaining this awesome project!

**Comment by felixmariotto** [comment]
Hi,

On the last three.js release, `Geometry` was removed, so the snippet you shared above can't be used anymore.
I'd be interested to know what you do when loading the hull parts from a gltf on three.js ^0.125.0

**Comment by marcofugaro** [comment]
@felixmariotto I was working on it in the [three-update](https://github.com/pmndrs/cannon-es/tree/three-update) branch, it works, however I'm still not happy about it code-wise.
It still needs the index array from the ConvexGeometry to calculate the faces, but I wanted to find a way to compute the faces starting from the vertices. 

Have a look at it, hopefully you find a solution.

**Comment by felixmariotto** [comment]
@marcofugaro 

I came up with this : 

```js
const hullBody = new CANNON.Body({
	mass,
	material
});

glb.scene.traverse( (obj) => {

	if ( obj.geometry ) {

		const posAttrib = obj.geometry.attributes.position;
		const vertices = [];

		for ( let i=0 ; i<posAttrib.count ; i++ ) {

			vertices.push(
				new CANNON.Vec3(
					posAttrib.getX( i ),
					posAttrib.getY( i ),
					posAttrib.getZ( i )
				)
			);

		}

		//

		const normAttrib = obj.geometry.attributes.normal;
		const normals = [];

		for ( let i=0 ; i<normAttrib.count ; i++ ) {

			normals.push(
				new CANNON.Vec3(
					normAttrib.getX( i ),
					normAttrib.getY( i ),
					normAttrib.getZ( i )
				)
			);

		}

		//

		const index = obj.geometry.index;
		const faces = [];

		for ( let i=0 ; i<index.count ; i+=3 ) {

			faces.push([
				index.array[ i ],
				index.array[ i + 1 ],
				index.array[ i + 2 ]
			]);

		}

		// Construct polyhedron

		const hullPart = new CANNON.ConvexPolyhedron({ vertices, faces, normals })

		// Add to compound

		hullBody.addShape( hullPart );

	}

});
```

No idea if it's optimal, I'm just starting with cannon.js.
Thank you for maintaining this fork btw !

**Comment by felixmariotto** [comment]
I've got this bug with the generated body though, do you think it's related to the way I'm making the composite hull ?

https://user-images.githubusercontent.com/46470486/107856840-4b3efb80-6e2b-11eb-8bd9-6de604ac52db.mp4

**Comment by marcofugaro** [comment]
@felixmariotto thanks! Any errors in the console?

**Comment by marcofugaro** [comment]
That is the funniest bug 😂

**Comment by felixmariotto** [comment]
@marcofugaro 

Nope no error in the console.

I use [V-HACD for Blender 2.8](https://github.com/andyp123/blender_vhacd) ( I use it in 2.91 though, could it be the problem ? ).
This is my options to convert a Suzanne mesh, is that different from the options you use ? It's the default, I only set `maximum concavity` to 0.

![Screenshot_1](https://user-images.githubusercontent.com/46470486/107857483-d79eed80-6e2e-11eb-9445-f22d35bada9d.png)

Would you have a GLB file that works correctly for you ? This way I could test if it comes from my model or from my code.

**Comment by Ithamar** [comment]
@felixmariotto if you are still having trouble, you might want to remove the normal handling part of the code you posted, since you are passing vertex normals to cannon, where it actually expects face normals.

**Comment by felixmariotto** [comment]
@Ithamar thanks a lot for this feedback ! I gave up with cannon entirely and made my own physics engine for my small usecase, but I'm sure this will be helpful for somebody.

**Comment by nikhilSriva** [comment]
@samuelbelolo How did you transform a regular mesh imported from a GLTF model into the v-hcad decomposition one?

**Comment by samuelbelolo** [comment]
> @samuelbelolo How did you transform a regular mesh imported from a GLTF model into the v-hcad decomposition one?

You need to decompose your mesh with your preferred 3D edition software. This is more a designer things to do. 
We used : [https://github.com/kmammou/v-hacd](https://github.com/kmammou/v-hacd)

you can also use this plugin for blender : [https://github.com/andyp123/blender_vhacd](https://github.com/andyp123/blender_vhacd)
