### ISSUE TITLE
expose wakeUp() in api

### ISSUE THREAD

**Issue by andreivips** [pmndrs/cannon-es#56]
Hi, and thanks for great libs ! 
Bodies falls asleep ( when `<Physics allowSleep={true}>` ), but after, wont move with applyImpulse/Force without wakeUp.

**Comment by marcofugaro** [comment]
Hey! Thanks!
Yeah it makes sense to wake up a sleeping body if a force/impulse is applied directly to it.

In the meantime, you have to call `body.wakeUp()`.

**Comment by andreivips** [comment]
... had to open it in useCannon
