### ISSUE TITLE
Split Solver constructor type

### ISSUE THREAD

**Issue by jf908** [pmndrs/cannon-es#57]
https://github.com/pmndrs/cannon-es/blob/f185940789c1f24f9b51ed1d3807b840f8274ea7/src/solver/SplitSolver.ts#L22

I believe the subsolver should have the type Solver or something else, and not SplitSolver otherwise it doesn't seem to be possible to construct this object.

**Comment by marcofugaro** [comment]
You're right, thanks for the catch!
