### ISSUE TITLE
World.time is twice what it should be 

### ISSUE THREAD

**Issue by nascheinkman** [pmndrs/cannon-es#81]
`World.time` is reporting a number twice that what it should.
 
I wrote a simple test case:
```
const world = new World()
for(let i = 0; i < 60; i++) {
  world.step(1/60)
}
expect(world.time).toBeCloseTo(1)
```
which fails with the message:
```
Expected: 1
Received: 1.9999999999999978
```
I looked at the world code and for a fixed time step the internal time counter is incremented twice, once here in the actual World.step function: https://github.com/pmndrs/cannon-es/blob/cebdad108d0d97ff9b67cb65562ed784821f13ea/src/world/World.ts#L395
and once here in the called World.internalStep function:
https://github.com/pmndrs/cannon-es/blob/cebdad108d0d97ff9b67cb65562ed784821f13ea/src/world/World.ts#L761

I'm not sure which one is the redundant one

**Comment by marcofugaro** [comment]
You're right! Thanks for reporting this!

The `world.time` property is used internally only for the sleeping mechanic, so nobody ever noticed it. 
I'll do a PR.
