### ISSUE TITLE
Error thrown when used in SparkAR, where cannon.js works

### ISSUE THREAD

**Issue by johannesrave** [pmndrs/cannon-es#86]
Heyhey,
first of all, thank you for maintaining this!

I'm using "vanilla" cannon.js in my SparkAR-projects (instagrams AR facefilter technology) and am writing a little wrapper for it. I install it using yarn into the project's script-directory, and from there I can work with it using TypeScript in WebStorm. As I understand it, SparkAR hot reloads the script files referenced in the project, after using webpack to bundle them to some temporary folder in the user directory - this is a bit of a black box.

To reduce bundle size in the face filter projects (and to work with a maintained library) I tried to switch from cannon to cannon-es. I also installed with yarn and can use the library completely normally with code-completion and type recognition. However, when importing cannon-es (or parts of it) into a new or ongoing project TypeScript-file and hot reloading, SparkAR throws this:

```
JavaScript error: Compiling JS failed: 14984:28:invalid expression Buffer size 1186988 starts with: 2866756e6374696f6e205f5f61726678
```

This is something happening internally of SparkAR to the bundled version of the script obviously, as it happens on line 14984, and I realize that it's not a problem of cannon-es per se. However, I have no idea how to debug this and haven't seen it with other libraries or modules. So I just wanted to ask if any of the contributers here have an idea what could be causing the `invalid expression Buffer size`. For the moment I still had to switch back to cannon.js, which is working fine.

If needed information is missing from my post, please let me know, and sorry if it isn't apropriate to ask this here.

**Comment by marcofugaro** [comment]
Thanks for the issue! Haven't tried SparkAR myself, could you maybe share a minimal reproducible project with cannon-es? It will help with debugging.
That error is kinda weird, will check if it's something we added in cannon-es.

**Comment by johannesrave** [comment]
Thanks a lot for your quick reply!
I attached a zipped "cannon-es_debuggingProject.arprojpkg", that's the packaged format for SparkAR-Studio projects. If you open it with [SparkAR](https://sparkar.facebook.com/ar-studio/download), it'll already do what this issue is about (on my system, anyway). If you want to play around with it, "save as" and it'll extract to a project directory where you point it to. That'll have the "scripts" subdir, where the .ts and the node_modules are etc.

The script is basically blank:
```
import D from 'Diagnostics';
import CANNON from 'cannon-es';

(async function () {
    D.log("Init cannon-es_Hook");

    const body = new CANNON.Body();
})();

```
It won't even print the log, as the error is thrown during compilation. With this empty-ish project, the line number is only "856".

![image](https://user-images.githubusercontent.com/31467653/111925395-043aca80-8aa9-11eb-9d24-f399fddedabf.png)

I guess finding the (bundled?) JS that SparkAR is trying to compile could help in finding out more. If you `yarn add cannon` and adjust the import, the log is printed to the SparkAR console. Let me know if you need anything else :)


[cannon-es_debuggingProject.zip](https://github.com/pmndrs/cannon-es/files/6178642/cannon-es_debuggingProject.zip)

**Comment by nicolashahn** [comment]
@johannesrave did you ever sort this out? Seeing something similar in Studio, though I'm not using cannon.js

**Comment by marcofugaro** [comment]
I've found the issue, you can't use npm modules directly from SparkAR, you have to add them as scripts:

<img width="701" alt="Screenshot 2021-12-28 at 16 14 58" src="https://user-images.githubusercontent.com/7217420/147582824-860dcb05-ad81-4dff-ad13-df9e45ff502c.png">

For cannon-es specifically, you have to use the [dist/cannon.cjs.js](https://github.com/pmndrs/cannon-es/blob/master/dist/cannon-es.cjs.js) file, and import it as

```js
import * as CANNON from './cannon-es'
```

I've made an example starter project with `cannon-es` already installed:

[cannon-es_working.arprojpkg.zip](https://github.com/pmndrs/cannon-es/files/7785381/cannon-es_working.arprojpkg.zip)

**Comment by johannesrave** [comment]
very cool, thank you @marcofugaro !
