### ISSUE TITLE
FBX Loader and Animations

### ISSUE THREAD

**Issue by NabeelUppel** [pmndrs/cannon-es#91]
Hi,  I'm trying to add a physics object onto a loaded fbx model. I managed to add a cannon cylinder around my model by using the dimensions of of bounding box around my model.
I'm  having issues trying to keep the cylinder around during animations. 

I can move the cylinder using:
```
CharacterBody.position.z += 5

//Sync model and mesh
Character.position.copy(CharacterBody.position)
Character.quaternion.copy(CharacterBody.quaternion)
```
But during a walk animation for example the model moves much quicker than the box itself. 

I know that the body has a velocity but I'm nor sure how to use it. 
I've tried:
```CharacterBody.velocity.z =5```
but nothing happens.

**Comment by marcofugaro** [comment]
First make sure your body has a mass. Then you should be able to move the body by setting its velocity. 

`CharacterBody.velocity.z = 5` should work fine.

Check out the [threejs_fps](https://pmndrs.github.io/cannon-es/examples/threejs_fps) example for a movement example.

**Comment by NabeelUppel** [comment]
My body does have a mass of 80 but still does not work:

Create body code:
```
const heavyMaterial = new CANNON.Material('heavy');
const characterShape = new CANNON.Cylinder(depth*0.75, depth*0.75, height, 8)         
this.CharacterBody = new CANNON.Body({
                mass: 80,
                position: new CANNON.Vec3(0, 0, 0)
                material: heavyMaterial            
});           
this.CharacterBody.addShape(characterShape,new CANNON.Vec3(0,height/2,0));
this.CharacterBody.angularDamping = 1;            
this.world.addBody(this.CharacterBody);
```

Controller Code:
```       
if (this.input.CharacterMotions.forward){
         this.CharacterBody.velocity.z = 5
}        
if (this.input.CharacterMotions.backward) {
         this.CharacterBody.velocity.z = -5        
}
     
this.Character.position.copy(this.CharacterBody.position)        
this.Character.quaternion.copy(this.CharacterBody.quaternion)
```

**Comment by marcofugaro** [comment]
You have to call world.step() to update the bodies positions based on their velocity, try:


```js
if (this.input.CharacterMotions.forward){
         this.CharacterBody.velocity.z = 5
}        
if (this.input.CharacterMotions.backward) {
         this.CharacterBody.velocity.z = -5        
}
     
// world.step() goes here

this.Character.position.copy(this.CharacterBody.position)        
this.Character.quaternion.copy(this.CharacterBody.quaternion)
```

Or just reorganize your code to call `world.step()` before copying the position.

Also your body mass might be too high, maybe increase the velocity amount?

**Comment by NabeelUppel** [comment]
Thank you. That worked. Also instead of changing my mass I increased the velocity.
