### ISSUE TITLE
How to rotate a body on key down..

### ISSUE THREAD

**Issue by NabeelUppel** [pmndrs/cannon-es#92]
I know this isn't the place to ask this, I'm very new to physics and games in general.  

How do I rotate a cannon body at a constant speed when holding down the "a" or "d" key. 

I'm trying to implement a controller for a fbx model and I'm having some issues regarding rotations and jumping. 

Currently for forward and jump I do something like:
```
If(jump){
Body.position.y+=5
}


if(forward){
Body.position.z+=5
}
```
Is this method fine or should I use velocity? The jump statement has been giving me some issue as well.

**Comment by marcofugaro** [comment]
You can rotate a body with

```js
body.rotation.y += 0.1
```

Please refer to the [FPS example](https://pmndrs.github.io/cannon-es/examples/threejs_fps) if you need more code relative to the movement.

For example here is the WASD movement:

https://github.com/pmndrs/cannon-es/blob/c58594f63d6c56caf8b11e9661dd0d16787b77a0/examples/js/PointerLockControlsCannon.js#L202-L214

**Comment by NabeelUppel** [comment]
`Body.rotation.y+=0,1`

Does not not work. I don't think body has a rotation object. It says it's undefined
