### ISSUE TITLE
Performance down in cannon.js v0.4.3 -> v0.6.2

### ISSUE THREAD

**Issue by cx20** [pmndrs/cannon-es#94]
It was a long time ago, so I don't remember much about it, but when I updated Cannon.js from `v0.4.3` to `v0.6.2`, there was a performance down. https://github.com/schteppe/cannon.js/issues/310
I tried the library with cannon-es and the performance seems to be similar.

three.js + cannon.js v0.4.3 result:
https://cx20.github.io/jsdo.it-archives/cx20/qM1k/

three.js + cannon.js v0.6.2 result:
https://cx20.github.io/jsdo.it-archives/cx20/CeNf/

I'm not sure who told me about it, but it seems to be improved by applying the following monkey patch.

```javascript
//////////////////////////////////////////////
//./cannon.js-0.6.2/src/math/Vec3.js + modified
//////////////////////////////////////////////
/**
 * @method tangents
 * @memberof CANNON.Vec3
 * @brief Compute two artificial tangents to the vector
 * @param CANNON.Vec3 t1 Vector object to save the first tangent in
 * @param CANNON.Vec3 t2 Vector object to save the second tangent in
 */
var Vec3_tangents_n = new CANNON.Vec3();
var Vec3_tangents_randVec = new CANNON.Vec3();
CANNON.Vec3.prototype.tangents = function(t1, t2) {
    const norm = this.length();
    if (norm > 0) {
        const n = Vec3_tangents_n;
        const inorm = 1 / norm;
        n.set(this.x * inorm, this.y * inorm, this.z * inorm);
        const randVec = Vec3_tangents_randVec;
        if (Math.abs(n.x) < 0.9) {
            randVec.set(1, 0, 0);
            n.cross(randVec, t1);
        } else {
            //randVec.set(0, 1, 0);
            randVec.set(0, 0, 0); // TODO: This is a monkey patch to improve performance. Changed from 1 to 0
            n.cross(randVec, t1);
        }
        n.cross(t1, t2);
    } else {
        t1.set(1, 0, 0);
        t2.set(0, 1, 0);
    }
}
```

The following is the result of applying the monkey patch.

three.js + cannon-es v0.17.1 + monkey patch result:
https://cx20.github.io/webgl-physics-examples/examples/threejs/cannon-es/domino/

I won't create a PR because I can't be certain that this fix is correct, but I hope it will help improve performance.

**Comment by marcofugaro** [comment]
Thanks for the suggestion.

Your monkey patch makes the cross product evaluate to 0, and the tangents as well, thus disabling the compute tangents part of the Narrowphase? I don't know exactly what it's affecting.

Have you tried adjusting the contact equation and other world parameters instead? These ones:
https://github.com/pmndrs/cannon-es/blob/28248468d27496ff3b029aa141b0a930505f8ac3/examples/container.html#L128-L140

**Comment by cx20** [comment]
Thank you for letting me know those parameters.
I will have to check the parameters a little more carefully, but I tried a little and didn't get the results I was expecting.

**Comment by marcofugaro** [comment]
@cx20 Looks like by using those settings, the dominos behave like your original example.

Check out the live demo here: https://codesandbox.io/s/r3f-cannon-dominos-forked-ds0kv?file=/src/App.js

**Comment by cx20** [comment]
@marcofugaro Thank you for telling me the sample. My sample seemed to improve by changing the `frictionEquationStiffness` parameter.

https://codesandbox.io/s/r3f-cannon-dominos-forked-ds0kv?file=/src/App.js:722-752
```
frictionEquationStiffness: 1e2
```
