### ISSUE TITLE
Bodies are null in beginContact and endContact events

### ISSUE THREAD

**Issue by petkoneo** [pmndrs/cannon-es#97]
Hello guys. I have a minor issue in my game development with materials bouncing of each other, which I would like to clamp to a specific speed during the endContact event which occurs on the world. This event emits two bodies, which are explicitly changed into null inside the framework:
```js
beginContactEvent.bodyA = beginContactEvent.bodyB = null;
```
as well as
```js
endContactEvent.bodyA = endContactEvent.bodyB = null;
```
 This creates multiple issues in the event handling process. Would you be able to repair it or just return the actual bodies?

 Thank you for the response.

**Comment by marcofugaro** [comment]
Hey. As you can see from the code, the `dispatchEvent()` is called first, and then the body references are freed.

https://github.com/pmndrs/cannon-es/blob/28248468d27496ff3b029aa141b0a930505f8ac3/src/world/World.ts#L868-L873

You probably are doing something asynchronous in your addEventListener callback, so I suggest you first save bodyA and bodyB in variables and then do the asynchronous bit.

```js
world.addEventListener('endContact', (event) => {
  const { bodyA, bodyB } = event

  // asynchronous bit, bodyA and bodyB are saved in the variables
})
```

Also, check out the [trigger example](https://github.com/pmndrs/cannon-es/blob/28248468d27496ff3b029aa141b0a930505f8ac3/examples/trigger.html#L54-L62), it correctly uses bodyA and bodyB there.

**Comment by petkoneo** [comment]
Yes that was the issue. Thanks for your help. :)
