### ISSUE TITLE
How can I make a sphere bounce inside a box?

### ISSUE THREAD

**Issue by JSmithOner** [pmndrs/cannon-es#98]
I would like to make a sphere bounce inside a box.
For the moment the sphere acts like there were a collision and quickly bounces off the cube when I position it at the center of box. I'm using THREE.js by the way. Many thanks in advance.

**Comment by marcofugaro** [comment]
Check out the Pile example: https://pmndrs.github.io/cannon-es/examples/pile

Basically you put a static plane for each side of the cube.

**Comment by JSmithOner** [comment]
thank you for your answer
