### ISSUE TITLE
Position Physics inside THREE.js group

### ISSUE THREAD

**Issue by JSmithOner** [pmndrs/cannon-es#99]
I have group of object, also all objects added to this group gets centered and the position (0,0,0) inherits from the group world position. My problem is that it's heavy and error prone.
I always need to subtract the position by half the size of my object. Is there a particular method to use in that case? If you can't get an answer I'll try making an example.
Thanks in advance,
(by the way I'm a newbie in the world of 3D and physics)

**Comment by marcofugaro** [comment]
You should not be using three.js groups when using physics engines, all your meshes should be added directly to the scene.

As you said, it's very error-prone. It's common knowledge not to use groups.

**Comment by JSmithOner** [comment]
Thank you for your quick answer, unfortunately I'm not creating a game. I'm making an editor with different objects that uses different physics world. i'm using group because it enables me to do global transform on an object. But tell me if I'm correct with the whole "object width/height/depth divided by 2" thing. Even if it's a headache that should work right?

**Comment by marcofugaro** [comment]
I don't have enough context to fully understand your issue, but yes, if you do some transforms before applying the position to the three.js mesh, it should work fine.

**Comment by JSmithOner** [comment]
ok thank you for the answer. Have a great day.
